version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: emsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    container_name: ems-backend
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "chmod +x mvnw && ./mvnw spring-boot:run"

volumes:
  mysql-data:
